In [1]:
import numpy as np
import csv

In [6]:
iris_data = []
with open('iris.csv') as csvfile:
    csv_reader = csv.reader(csvfile)
    birth_header = next(csv_reader)
    for row in csv_reader:
        iris_data.append(row)
iris_data

[['1', '5.1', '3.5', '1.4', '0.2', 'setosa'],
 ['2', '4.9', '3', '1.4', '0.2', 'setosa'],
 ['3', '4.7', '3.2', '1.3', '0.2', 'setosa'],
 ['4', '4.6', '3.1', '1.5', '0.2', 'setosa'],
 ['5', '5', '3.6', '1.4', '0.2', 'setosa'],
 ['6', '5.4', '3.9', '1.7', '0.4', 'setosa'],
 ['7', '4.6', '3.4', '1.4', '0.3', 'setosa'],
 ['8', '5', '3.4', '1.5', '0.2', 'setosa'],
 ['9', '4.4', '2.9', '1.4', '0.2', 'setosa'],
 ['10', '4.9', '3.1', '1.5', '0.1', 'setosa'],
 ['11', '5.4', '3.7', '1.5', '0.2', 'setosa'],
 ['12', '4.8', '3.4', '1.6', '0.2', 'setosa'],
 ['13', '4.8', '3', '1.4', '0.1', 'setosa'],
 ['14', '4.3', '3', '1.1', '0.1', 'setosa'],
 ['15', '5.8', '4', '1.2', '0.2', 'setosa'],
 ['16', '5.7', '4.4', '1.5', '0.4', 'setosa'],
 ['17', '5.4', '3.9', '1.3', '0.4', 'setosa'],
 ['18', '5.1', '3.5', '1.4', '0.3', 'setosa'],
 ['19', '5.7', '3.8', '1.7', '0.3', 'setosa'],
 ['20', '5.1', '3.8', '1.5', '0.3', 'setosa'],
 ['21', '5.4', '3.4', '1.7', '0.2', 'setosa'],
 ['22', '5.1', '3.7', '1.5', '0.4'

In [5]:
iris_list = []
for row in iris_data:
    iris_list.append(tuple(row[1:]))
iris_list

[('5.1', '3.5', '1.4', '0.2', 'setosa'),
 ('4.9', '3', '1.4', '0.2', 'setosa'),
 ('4.7', '3.2', '1.3', '0.2', 'setosa'),
 ('4.6', '3.1', '1.5', '0.2', 'setosa'),
 ('5', '3.6', '1.4', '0.2', 'setosa'),
 ('5.4', '3.9', '1.7', '0.4', 'setosa'),
 ('4.6', '3.4', '1.4', '0.3', 'setosa'),
 ('5', '3.4', '1.5', '0.2', 'setosa'),
 ('4.4', '2.9', '1.4', '0.2', 'setosa'),
 ('4.9', '3.1', '1.5', '0.1', 'setosa'),
 ('5.4', '3.7', '1.5', '0.2', 'setosa'),
 ('4.8', '3.4', '1.6', '0.2', 'setosa'),
 ('4.8', '3', '1.4', '0.1', 'setosa'),
 ('4.3', '3', '1.1', '0.1', 'setosa'),
 ('5.8', '4', '1.2', '0.2', 'setosa'),
 ('5.7', '4.4', '1.5', '0.4', 'setosa'),
 ('5.4', '3.9', '1.3', '0.4', 'setosa'),
 ('5.1', '3.5', '1.4', '0.3', 'setosa'),
 ('5.7', '3.8', '1.7', '0.3', 'setosa'),
 ('5.1', '3.8', '1.5', '0.3', 'setosa'),
 ('5.4', '3.4', '1.7', '0.2', 'setosa'),
 ('5.1', '3.7', '1.5', '0.4', 'setosa'),
 ('4.6', '3.6', '1', '0.2', 'setosa'),
 ('5.1', '3.3', '1.7', '0.5', 'setosa'),
 ('4.8', '3.4', '1.9', '0.2', 

In [11]:
datatype = np.dtype([("Sepal.Length", np.str_, 40),
                     ("Sepal.Width", np.str_, 40),
                     ("Petal.Length", np.str_, 40),
                     ("Petal.Width", np.str_, 40),
                     ("Species", np.str_, 40)])
print(datatype)

[('Sepal.Length', '<U40'), ('Sepal.Width', '<U40'), ('Petal.Length', '<U40'), ('Petal.Width', '<U40'), ('Species', '<U40')]


In [12]:
iris_data = np.array(iris_list,dtype = datatype)
iris_data

array([('5.1', '3.5', '1.4', '0.2', 'setosa'),
       ('4.9', '3', '1.4', '0.2', 'setosa'),
       ('4.7', '3.2', '1.3', '0.2', 'setosa'),
       ('4.6', '3.1', '1.5', '0.2', 'setosa'),
       ('5', '3.6', '1.4', '0.2', 'setosa'),
       ('5.4', '3.9', '1.7', '0.4', 'setosa'),
       ('4.6', '3.4', '1.4', '0.3', 'setosa'),
       ('5', '3.4', '1.5', '0.2', 'setosa'),
       ('4.4', '2.9', '1.4', '0.2', 'setosa'),
       ('4.9', '3.1', '1.5', '0.1', 'setosa'),
       ('5.4', '3.7', '1.5', '0.2', 'setosa'),
       ('4.8', '3.4', '1.6', '0.2', 'setosa'),
       ('4.8', '3', '1.4', '0.1', 'setosa'),
       ('4.3', '3', '1.1', '0.1', 'setosa'),
       ('5.8', '4', '1.2', '0.2', 'setosa'),
       ('5.7', '4.4', '1.5', '0.4', 'setosa'),
       ('5.4', '3.9', '1.3', '0.4', 'setosa'),
       ('5.1', '3.5', '1.4', '0.3', 'setosa'),
       ('5.7', '3.8', '1.7', '0.3', 'setosa'),
       ('5.1', '3.8', '1.5', '0.3', 'setosa'),
       ('5.4', '3.4', '1.7', '0.2', 'setosa'),
       ('5.1', '3.7', '1.

In [13]:
PetalLength = iris_data["Petal.Length"].astype(float)
PetalLength

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [14]:
np.sort(PetalLength)

array([1. , 1.1, 1.2, 1.2, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.4, 1.4,
       1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.6, 1.6,
       1.6, 1.6, 1.6, 1.6, 1.6, 1.7, 1.7, 1.7, 1.7, 1.9, 1.9, 3. , 3.3,
       3.3, 3.5, 3.5, 3.6, 3.7, 3.8, 3.9, 3.9, 3.9, 4. , 4. , 4. , 4. ,
       4. , 4.1, 4.1, 4.1, 4.2, 4.2, 4.2, 4.2, 4.3, 4.3, 4.4, 4.4, 4.4,
       4.4, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.6, 4.6, 4.6, 4.7,
       4.7, 4.7, 4.7, 4.7, 4.8, 4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9,
       5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.2,
       5.2, 5.3, 5.3, 5.4, 5.4, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.6, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.9, 5.9, 6. , 6. , 6.1, 6.1,
       6.1, 6.3, 6.4, 6.6, 6.7, 6.7, 6.9])

In [15]:
np.unique(PetalLength)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.9, 3. , 3.3, 3.5, 3.6,
       3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9,
       5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.3,
       6.4, 6.6, 6.7, 6.9])

In [16]:
np.sum(PetalLength)

563.7

In [17]:
np.mean(PetalLength)

3.7580000000000005

In [18]:
np.std(PetalLength)

1.759404065775303

In [19]:
np.var(PetalLength)

3.0955026666666665

In [20]:
np.min(PetalLength)

1.0

In [21]:
np.max(PetalLength)

6.9